***Variables***
${_menu_checkbox_demo}      //body/div[2]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/ul[1]/li[1]/ul[1]/li[2]/a[1]
${_titulo_checkbox}     //h3[text()='This would be a basic example to start with checkboxes using selenium.']
${_single_checkbox}     //input[@id='isAgeSelected']
${_multiple_checkbox_opcion1}     //label[text()="Option 1"]/input
${_multiple_checkbox_opcion2}     //label[text()="Option 2"]/input
${_boton_checkbox}     //input[@id='check1']
