***Variables***
${_titulo_formulario1}      //h3[text()="This would be your first example to start with Selenium."]
${_input_formulario1}       //input[@id="user-message"]
${_boton_formulario1}       //button[@type="button" and text()="Show Message"]
${_cerrar_ventana_emerjente}        //a[@id="at-cv-lightbox-close"]

${_titulo_formulario2}      //div[text()="Two Input Fields"]
${_input1_formulario2}      //input[@id="sum1"]
${_input2_formulario2}      //input[@id="sum2"]
${_boton_formulario2}       //button[text()="Get Total"]