***Variables***
${_menu_jquery}      //body/div[2]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/ul[1]/li[1]/ul[1]/li[7]/a[1]
${_titulo_jquery}      //h2[contains(text(),'Single Select - Search and Select country')]
${_select_country_jquery}       //select[@id="country"]
${_select_states_jquery}       //select[@class="js-example-basic-multiple select2-hidden-accessible"]
${_eliminar_select_states}      //span[contains(text(),'×')]
${_select_territories_jquery}       //select[@class="js-example-disabled-results select2-hidden-accessible"]
${_select_file_jquery}       //select[@id='files']
${_titulo2_jquery}       //h3[contains(text(),'Drop-down with Category related options')]