***Variables***
${_menu_radio_buttons}      //body/div[@id='easycont']/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/ul[1]/li[1]/ul[1]/li[3]/a[1]
${_titulo_radio_buttons}      //h3[text()='This is again simple example to start working with radio buttons using Selenium.']
${_radio_optradio}     optradio
${_boton_radio_optradio}     //button[@id='buttoncheck']
${_radio_gender}     gender
${_radio_ageGroup}     ageGroup
${_boton_groupr_radio}     //button[contains(text(),'Get values')]