***Variables***
${_menu_select_list}      //body/div[@id='easycont']/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/ul[1]/li[1]/ul[1]/li[4]/a[1]
${_titulo_select_list}      //h3[contains(text(),'This would be your first example on select dropd d')]
${_select_list}     //select[@id="select-demo"]
${_multiselect_list}     //select[@name="States"]//button[@id='printMe']//button[@id='printMe']
${_boton_firt}      //button[@id='printMe']
${_boton_all}      //button[@id='printAll']
${_option_Florida}      //option[@value='Florida']
${_option_Texas}        //option[@value='Texas']